### ISSUE TITLE
关于《js实现对象，两个对象会相互影响》

### ISSUE THREAD

**Issue by Codpoe** [linsir6/AndroidNote#2]
1. 函数`dui`是个构造函数，当通过`new`来调用时，`dui`内部的`this`指向的是当前新建出来的对象，所以`this.list`指向的是新建对象自己的list。

2. 原本程序的运行结果之所以会让人觉得“_dui,和_dui2是会想互影响的”，原因在于函数`_insert`和函数`print`内部的`list`指向的其实是外部全局的`list`。

3. 同理，修改后的程序运行结果其实也是不正确的。函数`dui`内部的`list`在去掉`this`前缀之后也是指向外部全局环境的`list`的，只是它在每次`new`操作的时候都被指向了传参进来的新数组。

   如果在修改后的程序后面再执行一次`_dui.print()`，你会发现`_dui`的`list`是跟`_dui2`的`list`一样的。

**Comment by linsir6** [comment]
好的，我会在第一时间修改，谢谢您～
