### ISSUE TITLE
请问大神你有写博客吗？给个地址吧，已关注，希望大神持续更新

### ISSUE THREAD

**Issue by daochushilang** [linsir6/AndroidNote#3]
请问大神你有写博客吗？给个地址吧，已关注，希望大神持续更新

**Comment by daochushilang** [comment]
写得很详细

**Comment by linsir6** [comment]
首先感谢您的关注，能够得到您的肯定，是我最大的动力，说实话，最近都没怎么整理，最近在搞IOS，以后会合理安排一下时间，以后每天都是会整理一部分的。 您可以访问 http://linsir.top
